import { Sparkles } from "lucide-react";
import { MotionDiv, MotionH3 } from "../common/motion-wrapper";
import { SummaryViewer } from "../summaries/summary-viewer";
import { cn } from "@/lib/utils";

const DEMO_SUMMARY = `
🌍 AI Just Took Over the Music Charts! 🎶🤖

Quick Overview
• 🎯 An AI-generated song just hit #1 on global charts—welcome to the future of music.
• 📌 This marks a huge turning point for AI in creative industries.

# Document Details
• 📄 Type: Viral News Summary
• 👥 For: Music lovers, tech enthusiasts, creators

# Key Highlights
• 🚀 An AI-generated track created by a solo developer topped Spotify Global Top 50
• ⭐ The AI was trained on 10,000+ pop hits to mimic human emotion and style
• 💫 Industry leaders like Universal and Sony are now exploring AI collabs

# Why It Matters
• 💡 This breakthrough blurs the line between human creativity and machine intelligence. The implications for artists, producers, and listeners are massive.

# Main Points
• 🎯 Main insight: AI can now create commercially successful music indistinguishable from humans
• 💪 Key strength: Rapid production, zero writer’s block, scalable creativity
• 🔥 Important outcome: Record labels are racing to invest in AI-music tools

# Bottom Line
• 💫 AI isn’t coming for your playlist—it’s already in it. Stay curious, stay creative.
`;

export default function DemoSection() {
  return (
    <section className="relative overflow-hidden py-16 lg:py-24">
      
      {/* 1. Background Blob (Purple/Pink Theme) */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
      >
        <div
          className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[hsl(var(--primary))] via-[#9333ea] to-[#db2777] opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72rem]"
          style={{
            clipPath:
              "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
          }}
        />
      </div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* 2. Header Content */}
        <div className="flex flex-col items-center text-center space-y-6 mb-12">
          
          {/* Badge */}
          <div className="inline-flex items-center justify-center p-2 rounded-xl bg-primary/10 border border-primary/20 backdrop-blur-sm">
            <Sparkles className="w-5 h-5 text-primary animate-pulse" />
          </div>

          <MotionH3
            initial={{ y: 20, opacity: 0 }}
            whileInView={{ y: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="font-bold text-3xl md:text-4xl max-w-3xl mx-auto leading-tight"
          >
            See how Docusense transforms raw text into <br className="hidden md:block" />
            <span className="bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
               crystal clear insights
            </span>
          </MotionH3>
          
          <p className="text-muted-foreground text-lg max-w-2xl">
            This is an actual output generated by our AI model. From messy articles to structured knowledge in seconds.
          </p>
        </div>

        {/* 3. The Viewer (Mock Window) */}
        <MotionDiv
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="flex justify-center"
        >
            {/* Window Container */}
            <div className="relative w-full max-w-4xl rounded-2xl border border-border/50 bg-background/50 shadow-2xl backdrop-blur-xl overflow-hidden ring-1 ring-white/10">
                
                {/* Window Header (Mac Style dots) */}
                <div className="flex items-center gap-2 px-4 py-3 border-b border-border/50 bg-muted/30">
                    <div className="w-3 h-3 rounded-full bg-red-400/80" />
                    <div className="w-3 h-3 rounded-full bg-yellow-400/80" />
                    <div className="w-3 h-3 rounded-full bg-green-400/80" />
                    <div className="ml-2 text-xs text-muted-foreground font-medium">AI Analysis Result</div>
                </div>

                {/* Content Area */}
                <div className="p-2 sm:p-6 bg-background/40">
                    <SummaryViewer summary={DEMO_SUMMARY} />
                </div>

            </div>
        </MotionDiv>

      </div>
    </section>
  );
}