import { Sparkles } from "lucide-react";
import { MotionDiv, MotionH3 } from "../common/motion-wrapper";
import { SummaryViewer } from "../summaries/summary-viewer";

// 👇 Updated Content optimized for Detailed View
// (Bullets hata diye hain, lambe paragraphs daale hain taake card full lage)
const DEMO_SUMMARY = `
# 🌍 AI Just Took Over the Music Charts

The music industry has just witnessed a historic disruption as an AI-generated track officially claimed the number one spot on the Global Top 50. This isn't just a novelty act; it represents a seismic shift in how music is composed, produced, and consumed. The track, indistinguishable from human-made pop hits, was generated by a solo developer using advanced algorithms, proving that the barrier to entry for global stardom has fundamentally collapsed. This event signals the arrival of a new era where creativity is augmented by machine intelligence, challenging our traditional understanding of artistry and fame.

# 🧠 The Technology Behind the Hit

The underlying technology behind this breakthrough is a sophisticated deep-learning model trained on a dataset of over 10,000 chart-topping songs from the last decade. Unlike previous iterations of AI music which sounded robotic or disjointed, this new model captures the nuances of human emotion, cadence, and lyrical depth. It analyzes patterns in melody and rhythm to construct compositions that resonate psychologically with listeners. This level of fidelity proves that AI can now replicate the "human touch," raising fascinating questions about the definition of authorship in the digital age.

# 🔥 Impact on Record Labels & Artists

Major record labels like Universal and Sony are reacting swiftly to this disruption, racing to invest in similar technologies. Instead of fighting the tide, the industry is pivoting to integrate AI tools into production workflows. For independent artists, this democratizes high-quality production, eliminating the need for expensive studio time. However, it also creates significant anxiety regarding copyright, royalties, and competition. The industry is currently scrambling to establish legal frameworks that protect human artists while embracing the efficiency and innovation that generative AI brings to the table.

# 💡 A Hybrid Future for Creativity

As we look to the future, the line between human and machine-generated art will continue to blur, leading to a "Hybrid Creativity" model. This breakthrough suggests a future where AI serves as a sophisticated co-pilot for musicians, handling the technical heavy lifting while humans focus on high-level creative direction. We are moving towards a world of hyper-personalized music, where listeners might generate custom soundtracks for their lives on the fly. The success of this track is just the beginning; the revolution is already in your playlist, demanding that we stay curious and open to new forms of expression.
`;

export default function DemoSection() {
  return (
    <section className="relative overflow-hidden py-16 lg:py-24">
      
      {/* 1. Background Blob (Purple/Pink Theme) */}
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-x-0 -top-40 -z-10 transform-gpu overflow-hidden blur-3xl sm:-top-80"
      >
        <div
          className="relative left-[calc(50%-11rem)] aspect-[1155/678] w-[36.125rem] -translate-x-1/2 rotate-[30deg] bg-gradient-to-tr from-[hsl(var(--primary))] via-[#9333ea] to-[#db2777] opacity-20 sm:left-[calc(50%-30rem)] sm:w-[72rem]"
          style={{
            clipPath:
              "polygon(74.1% 44.1%, 100% 61.6%, 97.5% 26.9%, 85.5% 0.1%, 80.7% 2%, 72.5% 32.5%, 60.2% 62.4%, 52.4% 68.1%, 47.5% 58.3%, 45.2% 34.5%, 27.5% 76.7%, 0.1% 64.9%, 17.9% 100%, 27.6% 76.8%, 76.1% 97.7%, 74.1% 44.1%)",
          }}
        />
      </div>

      <div className="container mx-auto px-4 sm:px-6 lg:px-8 relative z-10">
        
        {/* 2. Header Content */}
        <div className="flex flex-col items-center text-center space-y-6 mb-12">
          
          {/* Badge */}
          <div className="inline-flex items-center justify-center px-3 py-1 rounded-full bg-primary/10 border border-primary/20 backdrop-blur-sm text-xs font-medium text-primary mb-2">
            <Sparkles className="w-3.5 h-3.5 mr-2 animate-pulse" />
            Live Demo
          </div>

          <MotionH3
            initial={{ y: 20, opacity: 0 }}
            whileInView={{ y: 0, opacity: 1 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="font-bold text-3xl md:text-4xl max-w-3xl mx-auto leading-tight text-foreground"
          >
            See how Docusense transforms raw text into <br className="hidden md:block" />
            <span className="bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
               crystal clear insights
            </span>
          </MotionH3>
          
          <p className="text-muted-foreground text-lg max-w-2xl">
            Experience the actual output generated by our AI. From messy articles to structured knowledge cards.
          </p>
        </div>

        {/* 3. The Viewer (No Window Frame, Just the Card) */}
        <MotionDiv
            initial={{ opacity: 0, y: 40 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="relative w-full max-w-4xl mx-auto"
        >
            {/* Glow Effect behind the card */}
            <div className="absolute inset-0 bg-primary/10 blur-[60px] rounded-full -z-10 transform scale-95" />
            
            {/* The Actual Component */}
            <SummaryViewer summary={DEMO_SUMMARY} />

        </MotionDiv>

      </div>
    </section>
  );
}