"use client";
import { Button } from "@/components/ui/button";
import { Download } from "lucide-react";

export function DownloadSummaryButton({
  title,
  summaryText,
  fileName,
  createdAt,
}: {
  title: string;
  summaryText: string;
  fileName: string;
  createdAt: string;
}) {
  const handleDownload = () => {
    // 👇 Content Update: Branding change (Summarie -> Docusense AI)
    const summaryContent = `# ${title}
AI Generated Summary
Date: ${new Date(createdAt).toLocaleDateString()}

${summaryText}

Original File: ${fileName}
Generated by Docusense AI
`;

    const blob = new Blob([summaryContent], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `Docusense-${title.replace(/[^a-z0-9]/gi, "_")}.txt`;
    document.body.appendChild(link);
    link.click();

    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <Button
      variant="outline"
      size="sm"
      className="gap-2 border-primary/20 bg-primary/5 text-primary hover:bg-primary/10 hover:text-primary hover:border-primary/40 transition-all shadow-sm"
      onClick={handleDownload}
    >
      <Download className="h-4 w-4" />
      Download Summary
    </Button>
  );
}